# Generated by Django 2.0.7 on 2018-08-13 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_auto_20180813_1603'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='contact_no',
            new_name='mobile',
        ),
    ]
