# Generated by Django 2.0.7 on 2018-08-21 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0005_auto_20180820_1717'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='department',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
