# Generated by Django 2.0.7 on 2018-08-13 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='contact_no',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
