# Generated by Django 2.0.7 on 2018-08-19 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0007_auto_20180806_1746'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='contact_person3',
            field=models.CharField(blank=True, max_length=24, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='is_active',
            field=models.CharField(choices=[('YES', 'Yes'), ('NO', 'No')], default='YES', max_length=254),
        ),
        migrations.AddField(
            model_name='organization',
            name='mobile3',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
