# Generated by Django 2.0.7 on 2019-02-23 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0009_auto_20190212_1358'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organization',
            old_name='contact_person1',
            new_name='mobile',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='contact_person2',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='contact_person3',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='logo',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='mobile1',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='mobile2',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='mobile3',
        ),
        migrations.AddField(
            model_name='organization',
            name='username',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='address',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
