# Generated by Django 2.0.7 on 2018-07-30 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='ticket_type',
            field=models.CharField(choices=[('PROBLEM', 'Problem'), ('FEATURE REQUIRED', 'Feature Required'), ('SUGGESTION', 'Suggestion')], max_length=2),
        ),
    ]
