# Generated by Django 2.0.7 on 2018-08-14 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_auto_20180813_1802'),
        ('tickets', '0005_auto_20180813_2222'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='employee_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employees.Employee'),
        ),
    ]
