# Generated by Django 2.0.7 on 2018-08-15 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0008_auto_20180814_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='issue_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
