# Generated by Django 2.0.7 on 2018-08-22 02:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('tickets', '0010_auto_20180819_1320'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='product_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.Product'),
        ),
    ]
