# Generated by Django 2.0.7 on 2018-07-27 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=40)),
                ('contact', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=50)),
                ('contact_person', models.CharField(max_length=25)),
            ],
        ),
    ]
