# Generated by Django 2.0.7 on 2018-08-06 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0004_auto_20180806_1344'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organization',
            old_name='contact_person',
            new_name='contact_person1',
        ),
        migrations.AddField(
            model_name='organization',
            name='contact_person2',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='mobile1',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='mobile2',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
