# Generated by Django 2.0.7 on 2018-07-30 07:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0003_auto_20180730_1333'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_type', models.CharField(choices=[('PR', 'Problem'), ('FR', 'Feature Required'), ('SG', 'Suggestion')], max_length=2)),
                ('description', models.TextField(max_length=400)),
                ('issue_date', models.DateField()),
                ('completion_date', models.DateField()),
                ('status', models.CharField(choices=[('O', 'Open'), ('C', 'Close'), ('P', 'Pending')], max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.Organization')),
            ],
        ),
    ]
