# Generated by Django 2.0.7 on 2018-08-13 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_auto_20180730_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Open'), ('CLOSE', 'Close'), ('PENDING', 'Pending')], default='OPEN', max_length=10),
        ),
    ]
