# Generated by Django 2.0.7 on 2018-08-14 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0007_ticket_attached_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='attached_file',
            field=models.ImageField(blank=True, null=True, upload_to='ticket_file/'),
        ),
    ]
