# Generated by Django 2.0.7 on 2019-02-23 05:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0012_branch_problemdomain'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='organization_id',
            new_name='client_id',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='attached_file',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='completion_date',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='description',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='product_id',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='ticket_type',
        ),
        migrations.AddField(
            model_name='ticket',
            name='branch_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tickets.Branch'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='problem_domain_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tickets.ProblemDomain'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='remarks',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='source',
            field=models.CharField(choices=[('CALL_IN', 'Call in'), ('CALL_OUT', 'Call_out'), ('CUG', 'CUG'), ('VIBER', 'Viber'), ('SKYPE', 'Skype')], default='CALL_IN', max_length=10),
        ),
        migrations.AddField(
            model_name='ticket',
            name='ticket',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
