# Generated by Django 2.0.7 on 2019-03-10 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0013_auto_20190223_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='source',
            field=models.CharField(choices=[('Call_in', 'Call_in'), ('Call_out', 'Call_out'), ('CUG', 'CUG'), ('Viber', 'Viber'), ('Skype', 'Skype'), ('Message', 'Message')], default='Call_in', max_length=10),
        ),
    ]
