# Generated by Django 2.0.7 on 2019-03-10 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0014_auto_20190310_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='source',
            field=models.CharField(choices=[('call_in', 'call_in'), ('Call_out', 'Call_out'), ('CUG', 'CUG'), ('Viber', 'Viber'), ('Skype', 'Skype'), ('Message', 'Message')], default='call_in', max_length=10),
        ),
    ]
