# Generated by Django 2.0.7 on 2019-03-14 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0015_auto_20190310_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='client_id',
            field=models.CharField(max_length=255),
        ),
    ]
