# Generated by Django 2.0.7 on 2019-03-15 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0017_auto_20190314_2137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('Open', 'Open'), ('Close', 'Close'), ('Pending', 'Pending')], default='Open', max_length=10),
        ),
    ]
