# Generated by Django 2.0.7 on 2019-03-18 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0018_auto_20190315_1601'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='contact',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ticket',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
